### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Madji** [citronalco/carddav2asterisk#1]
TabError: inconsistent use of tabs and spaces in indentation

**Comment by citronalco** [comment]
On Windows or Linux? Did you clone the repository are have you just copy-pasted the code?
I can't reproduce your issue, that's why I'm asking.

**Comment by Madji** [comment]
Debian 8 amd 64
Python 3.4
 File "./carddav2asterisk.py", line 30
    type = record.xpath(".//d:getcontenttype",namespaces={"d" : "DAV:"})
                                                                       ^
TabError: inconsistent use of tabs and spaces in indentation

I`m clone you git. 
Write a python should stand. what's the problem.
