### ISSUE TITLE
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

### ISSUE THREAD

**Issue by mgodiya** [citronalco/carddav2asterisk#10]
Hey All,

I am not an expert in python programming, but I believe I have done all things right.
I am getting the following error
```
Traceback (most recent call last):
  File "carddav2asterisk.py", line 90, in <module>
    main()
  File "carddav2asterisk.py", line 57, in main
    loop.run_until_complete(putCids(loop, args, config))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "carddav2asterisk.py", line 73, in putCids
    for vurl in getAllVcardLinks(url, auth):
  File "carddav2asterisk.py", line 25, in getAllVcardLinks
    root = etree.XML(r.text)
  File "src/lxml/lxml.etree.pyx", line 3192, in lxml.etree.XML (src/lxml/lxml.etree.c:78756)
  File "src/lxml/parser.pxi", line 1843, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118275)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```
here are my configs:
carddav2asterisk.ini:
```
[ami]
user = carddavimport
pass = TopSecret
host = localhost
port = 5038

[carddav]
url = https://cal.DOMAIN.TLD/caldav.php/EMAIL@DOMAIN.TLD/addresses/
user = EMAIL@DOMAIN.TLD
pass = PASSWORD
```
carddav2asterisk.conf:
```
[carddavimport]
secret = TopSecret
permit = 127.0.0.1/255.255.255.0
write = system
```

I am running the program like so: 
```
python3 /etc/asterisk/manager.d/carddav2asterisk.py /etc/asterisk/manager.d/carddav2asterisk.ini
```

Please suggest.

**Comment by citronalco** [comment]
Can you try what happens when you replace in line 25
`root = etree.XML(r.text)`
with
`root = etree.XML(r.text.encode())`
?

**Comment by mgodiya** [comment]
Thanks for the prompt reply,
it worked without errors.
But I cant seem to find my contacts in my GUI?
Also, I see that I dont have any output on the screen.
I will keep troubleshooting and Please let me know if you have any ideas.

**Comment by citronalco** [comment]
What CardDav server/service do you use?

**Comment by mgodiya** [comment]
i am using davical om debian
```
ap-get install davical
```

**Comment by citronalco** [comment]
Davical is more picky than Nextcloud.
I've made some changes. Can you check if it works now?

**Comment by mgodiya** [comment]
Genius!!
it works.
Now I will just edit the script as my contacts are in mixed formats
i.e., some international, 11 digit, 10 digit and 7 digit.
I know! my cardbook is a mess, but I'll make sure I pull/send you my code to publish.
And again, thanks a million.
