### ISSUE TITLE
StopIteration

### ISSUE THREAD

**Issue by mokkin** [citronalco/carddav2asterisk#6]
When fetching vCards from another CardDAV-Server (type unknown) I am not succesful an get the following error:
```
Traceback (most recent call last):
  File "./carddav2asterisk.py", line 73, in <module>
    sys.exit(main(sys.argv))
  File "./carddav2asterisk.py", line 57, in main
    vcard = vobject.readOne(r.content)
  File "/usr/lib/python2.7/site-packages/vobject/base.py", line 1078, in readOne
    ignoreUnreadable, allowQP).next()
StopIteration
```
Maybe it is related to https://github.com/andig/carddav2fb/issues/50
Any ideas?

**Comment by citronalco** [comment]
Could be it's related to that, at least something similar. Seems to be a bug either in the CardDAV server or in the vobject library. The only thing that could be done here would be skipping all unreadable vcards - in the worst case that could be all of them.

carddav2asterisk is still based on Python2 which has it flaws.
I've seen someone forked carddav2asterisk and ported it to Python3.
Maybe you might want to give it a try: https://github.com/tbhi/carddav2asterisk
If you do it would be nice if you could drop me a line how it performs.

**Comment by citronalco** [comment]
Switched to Python3 in the meantime.
